### ISSUE TITLE
Many conflicts in the given conda environment

### ISSUE THREAD

**Issue by MOr1s2** [n3il666/Meta-DMoE#1]
When I want to create the conda environment with given environment.yml, there are many conflicts between the package with specified version. Would you mind telling me whether I missed some preparation or not? Or is there another way to create the required environment?( pip doesn't seem to work either) Thank you so much!

**Comment by n3il666** [comment]
Hi there, thanks for raising the issue. Seems like it is caused by recent torch updates. I am not too sure what happened to the environment.yml file but the `pip install -r requirements.txt` should work fine now. Let us know if it is resolved.

**Comment by MOr1s2** [comment]
> Hi there, thanks for raising the issue. Seems like it is caused by recent torch updates. I am not too sure what happened to the environment.yml file but the `pip install -r requirements.txt` should work fine now. Let us know if it is resolved.

Oh it does work, thank you so much!
